repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
            files: '^(java/.*\.java|py.*\.py)$'
          - id: trailing-whitespace
            files: '^(java/.*\.java|py.*\.py)$'
          - id: mixed-line-ending
            args: ['--fix=auto']
            files: '^(java/.*\.java|py.*\.py)$'
          - id: check-yaml
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.15.0
      hooks:
          - id: pretty-format-java
            args: [--autofix, --google-java-formatter-version=1.28.0]
            files: '^java/.*\.java$'
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.10.0
      hooks:
          - id: commitizen
            stages: [commit-msg]
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            language_version: python3
            files: '^py.*\.py$'
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ['--profile', 'black']
            files: '^py.*\.py$'
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.18.2
      hooks:
          - id: mypy
            files: '\.py$'
            args: [
                "--ignore-missing-imports",
                "--show-error-codes",
                "--explicit-package-bases",
                "--allow-untyped-defs",
                "--allow-incomplete-defs", 
                "--allow-untyped-calls",
                "--no-strict-optional",
                "--disable-error-code=misc",
                "--disable-error-code=no-any-return",
                "--disable-error-code=name-defined",
                "--disable-error-code=attr-defined"
            ]
            additional_dependencies: [ # Continue to add dependencies here that have mypy extensions, such as pydantic
                "types-requests",
                "types-toml",
                "pandas-stubs",
                "numpy"
            ]
    - repo: https://github.com/pamoller/xmlformatter
      rev: v0.2.8
      hooks:
          - id: xml-formatter
            files: '^.*\.xml$'
